### ISSUE TITLE
Can't play after go to menu

### ISSUE THREAD

**Issue by khoalex** [DaniellMesquita/Phonemon#1]
When I go to menu, I can't return to game because a message saying that I'm offline, but my connection is live.
Actual Build: [12068](https://github.com/DaniellMesquita/Phonemon/releases/tag/12.0.6.8)
![11846231_518737034948385_1052543417_n](https://cloud.githubusercontent.com/assets/13650571/9074743/07918d16-3ae3-11e5-8207-d831cd14ec6d.jpg)

**Comment by danimesq** [comment]
The connection is detected as live, but when trying return to game, shows this message. Soon I'll investigate and fix this. Thanks for testing and sending your feedback! You're welcome.

**Comment by danimesq** [comment]
This problem ocurred because I develop the game being offline, and I've incompletly removed the events of play button for I can play offline. Sorry for my desatention on these events that caused this problem. Fixed now.
