### ISSUE TITLE
Fix missing texts in route 1's plates

### ISSUE THREAD

**Issue by xandexs** [DaniellMesquita/Phonemon#4]
The texts in the guide plates in the route doesn't appear.
Actual Build: [12068](https://github.com/DaniellMesquita/Phonemon/releases/tag/12.0.6.8)

**Comment by danimesq** [comment]
Sorry, I've missed to add these stuffs for work on Route 1. Thank you for feedback, soon I'll fix this.

**Comment by danimesq** [comment]
Problem fixed!

**Comment by nrstmss** [comment]
problem?!

**Comment by nrstmss** [comment]
hm???!!!
